name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_REPO }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  build_push_platform:
    name: Build and Push Platform Service to Docker Hub
    needs: login
    runs-on: ubuntu-latest
    env:
      TAG: $(date +%s)
      IMAGE_NAME: platform_service
    steps:
    - uses: actions/checkout@v3
    - name: Build Platform Service the Docker image
      run: docker build ./PlatformService/Dockerfile --file Dockerfile --tag ${{ secrets.DOCKER_HUB_REPO }}/$IMAGE_NAME:$(date +%s) --tag ${{ secrets.DOCKER_HUB_REPO }}/$IMAGE_NAME:latest
    - name: Publish to Docker Hub
      run: docker push --all-tags ${{ secrets.DOCKER_HUB_REPO }}/$IMAGE_NAME
  build_push_command:
    name: Build and Push Command Service to Docker Hub
    needs: login
    runs-on: ubuntu-latest
    env:
      TAG: $(date +%s)
      IMAGE_NAME: command_service
    steps:
    - uses: actions/checkout@v3
    - name: Build Platform Service the Docker image
      run: docker build ./CommandsService/Dockerfile --file Dockerfile --tag ${{ secrets.DOCKER_HUB_REPO }}/$IMAGE_NAME:$(date +%s) --tag ${{ secrets.DOCKER_HUB_REPO }}/$IMAGE_NAME:latest
    - name: Publish to Docker Hub
      run: docker push --all-tags ${{ secrets.DOCKER_HUB_REPO }}/$IMAGE_NAME
