name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  platform:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_REPO }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPO }}/platform_service:latest
          # build-args: |
          #   RABBITMQ_VERSION=3.11.3-management
